<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>6cc35b35-5567-4107-8274-e82af9298ddd</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="9.0.13" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="9.0.13">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Design" Version="9.0.12" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="9.0.6" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\AdminPanel.Core\AdminPanel.Core.csproj" />
    <ProjectReference Include="..\AdminPanel.Repositories\AdminPanel.Repositories.csproj" />
    <ProjectReference Include="..\AdminPanel.Services\AdminPanel.Services.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Content Update="appsettings.Production.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <CopyToPublishDirectory>Always</CopyToPublishDirectory>
    </Content>
    <Folder Include="wwwroot\Files\Images\Brands\" />
    <Folder Include="wwwroot\Files\Images\categories\" />
    <Folder Include="wwwroot\Files\Images\Products\main\" />
    <Folder Include="wwwroot\Files\Images\Products\" />
    <Folder Include="wwwroot\Files\Images\Products\Sub\" />
  </ItemGroup>

</Project>
